const getObjectEntries = o => Object.entries(o); //; Your code here...
const getObjectKeys = o => Object.keys(o); //; Your code here...
const getObjectValues = o => Object.values(o); //; Your code here...

module.exports = {
    getObjectEntries,
    getObjectKeys,
    getObjectValues
};